matches:

- label: zoom link
  replace: https://link.indeed.tech/tonyyu
  trigger: zoom;;

- label: go.indeed.com link
  replace: https://link.indeed.tech/
  trigger: go;;

- label: Imhotep time
  trigger: imtime;;
  replace: IMHOTEP_UNIXTIME('{{shortdate}} 00:00:00')
  vars:
    - name: shortdate
      type: date
      params:
        format: "%Y-%m-%d"
