matches:
- label: Eval and feedback
  trigger: qfeedback;;
  replace: |
    ### [[Eval and Feedback - 2026-H1]]

    #### Strengths

    #### Areas for improvement

    #### Feedback request notes

- label: Block quote
  replace: |
    > [!quote]
    > 
  trigger: quote;;

- label: Aliases
  replace: |
    ---
    aliases: []
    ---
  trigger: aliases;;
