"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"

[[blocks]]
alignment = "left"
type = "prompt"

    [[blocks.segments]]
    foreground = "p:os"
    style = "plain"
    template = "{{.Icon}} "
    type = "os"

    [[blocks.segments]]
    foreground = "p:blue"
    style = "plain"
    template = "{{ .UserName }}@{{ .HostName }} "
    type = "session"

    [[blocks.segments]]
    foreground = "p:pink"
    style = "plain"
    template = "{{ .Path }} "
    type = "path"

        [blocks.segments.properties]
        folder_icon = "...."
        home_icon = "~"
        style = "agnoster_short"

    [[blocks.segments]]
    foreground = "p:lavender"
    template = """ {{ .UpstreamIcon }}{{ .HEAD }}\
      {{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
      {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
      {{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}\
      {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
      {{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }}\
    """
    style = "plain"
    type = "git"

        [blocks.segments.properties]
        fetch_stash_count = true
        fetch_status = true
        fetch_upstream_icon = true

        branch_icon = " "
        cherry_pick_icon = " "
        commit_icon = " "
        merge_icon = " "
        no_commits_icon = " "
        rebase_icon = " "
        revert_icon = " "
        tag_icon = " "

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

    [[blocks.segments]]
    foreground = "#fff"
    style = "plain"
    template = " ⚡ "
    type = "root"

    [[blocks.segments]]
    style = "plain"
    foreground = "p:closer"
    template = ""
    type = "text"
