---
# Generic dev tools

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask apps
  homebrew_cask:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_cask_apps }}'
  tags:
  - cask

- name: Ensure .config directories exists
  file:
    path: '{{ item }}'
    state: directory
  loop: '{{ config_directories }}'

- name: Link configs
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop: '{{ link_configs }}'
