---
# Generic dev tools

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask apps
  homebrew_cask:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_cask_apps }}'
  tags:
  - cask

- name: Install and setup nvm
  shell: |
    nvm install {{ node_version }}
    nvm alias default {{ node_version }}
    nvm use {{ node_version }}
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
  - neovim
  - node
