---
# Generic dev tools

- name: Ensure .zshrc exists
  ansible.builtin.file:
    dest: "~/.zshrc"
    state: touch
    modification_time: preserve
    access_time: preserve
  tags:
    - zsh

- name: Ensure .zshrc sources ~/dotfiles/zshrc
  ansible.builtin.lineinfile:
    dest: "~/.zshrc"
    line: "source ~/dotfiles/zshrc"
  tags:
    - zsh

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask apps
  homebrew_cask:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_cask_apps }}'
  tags:
  - cask

- name: Install and setup nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install {{ node_version }}
    nvm alias default {{ node_version }}
    nvm use {{ node_version }}
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
  - neovim
  - node
