---

# See neovim docs: https://neovim.io/doc/user/provider.html
- name: Set up neovim python provider
  command: >
    pyenv virtualenv {{ pyenv_python_versions|first }} py3nvim
    pyenv activate py3nvim
    pip install pynvim
  register: pyenv_install_result
  failed_when: >
    pyenv_install_result.rc != 0 and
    pyenv_install_result.stderr is not match("pyenv-virtualenv.* already exists")
  tags:
  - neovim
