---

- name: Ensure python venv directory exists
  file:
    path: "{{ python_venv_root }}"
    state: directory

# See neovim docs: https://neovim.io/doc/user/provider.html
- name: Set up neovim python provider
  shell: |
    {{ python_executable }} -m venv {{python_venv_root}}/py3nvim
    source {{python_venv_root}}/py3nvim/bin/activate
    pip install pynvim
  args:
    creates: "{{ python_venv_root }}/py3nvim"
  tags:
  - neovim

# See neovim docs: https://neovim.io/doc/user/provider.html
- name: Set up neovim node provider
  shell: |
    npm install -g neovim
  tags:
  - neovim
