---
# If pyenv fails, check https://github.com/pyenv/pyenv/wiki/Common-build-problems
- name: Install python through pyenv
  command: pyenv install {{ item }}
  environment:
    CONFIGURE_OPTS: --enable-optimizations
  register: pyenv_install_result
  failed_when: >
    pyenv_install_result.rc != 0 and
    pyenv_install_result.stderr is not match("pyenv: .* already exists")
  loop: '{{ pyenv_python_versions }}'
  tags:
  - python
  - pyenv

- name: Initialize versions using `pyenv global`
  command: pyenv global {{ pyenv_python_versions|join(" ") }}
  tags:
  - python
  - pyenv
