---

- name: Tap required Homebrew repositories
  community.general.homebrew_tap:
    name: '{{ item }}'
  loop: '{{ homebrew_taps }}'
  tags:
  - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask apps
  homebrew_cask:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_cask_apps }}'
  tags:
  - cask

- name: Ensure .config directory exists
  file:
    path: "~/.config"
    state: directory

- name: Link neovim config
  file:
    src: "~/dotfiles/vim"
    dest: "~/.config/nvim"
    state: link

- name: Ensure python venv directory exists
  file:
    path: "{{ python_venv_root }}"
    state: directory
  tags:
  - python

# See neovim docs: https://neovim.io/doc/user/provider.html
- name: Create py3nvim virtual environment
  shell: |
    {{ python_executable }} -m venv {{python_venv_root}}/py3nvim
  args:
    creates: "{{ python_venv_root }}/py3nvim"
  tags:
  - python

# See neovim docs: https://neovim.io/doc/user/provider.html
- name: Install pip dependencies in py3nvim virtual environment
  pip:
    name: '{{ venv_pip_packages }}'
    virtualenv: "{{python_venv_root}}/py3nvim"
  tags:
  - python


# See neovim docs: https://neovim.io/doc/user/provider.html
- name: Set up neovim node provider
  shell: |
    npm install -g neovim
  tags:
  - node
