---

custom_dir: "{{ lookup('env','ZSH_CUSTOM') | default('~/.oh-my-zsh/custom', true) }}"

homebrew_packages:
- starship


link_configs:
- src: "~/dotfiles/starship.toml"
  dest: "~/.config/starship.toml"
