---

homebrew_packages:
- oh-my-posh

homebrew_cask_apps: []

config_directories:
- "~/.config"
- "~/.config/ohmyposh"
- "~/.config/zinit"

# FIXME: Delete starship
link_configs:
- src: "~/dotfiles/config/terminal/starship.toml"
  dest: "~/.config/starship.toml"
- src: "~/dotfiles/config/terminal/ohmyposh.toml"
  dest: "~/.config/ohmyposh/ohmyposh.toml"
- src: "~/dotfiles/zinit"
  dest: "~/.config/zinit/zinit.git"
- src: "~/dotfiles/config/shell/zshenv"
  dest: "~/.zshenv"
