---

- name: Ensure .zshrc exists
  ansible.builtin.file:
    dest: "~/.zshrc"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Ensure .zshrc sources ~/dotfiles/zshrc
  ansible.builtin.lineinfile:
    dest: "~/.zshrc"
    line: "source ~/dotfiles/zshrc"

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Ensure .config directory exists
  file:
    path: "~/.config"
    state: directory

- name: Link configs
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop: '{{ link_configs }}'

- name: Clone zsh-autosuggestions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ custom_dir }}/plugins/zsh-autosuggestions"
