---

- name: Update dotfiles submodules
  ansible.builtin.shell: |
    git submodule update --init
  args:
    chdir: "~/dotfiles"

- name: Ensure .zshrc exists
  ansible.builtin.file:
    dest: "~/.zshrc"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Ensure .zshrc sources ~/dotfiles/zshrc
  ansible.builtin.lineinfile:
    dest: "~/.zshrc"
    line: "source ~/dotfiles/zshrc"

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Ensure .config directories exists
  file:
    path: '{{ item }}'
    state: directory
  loop: '{{ config_directories }}'

- name: Link configs
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop: '{{ link_configs }}'
